export type LandingCopy = {
  metaTitle: string;
  metaDescription: string;
  navBrand: string;
  navHow: string;
  navFeatures: string;
  addToDiscord: string;
  login: string;
  oauthNotConfiguredTitle: string;
  oauthNotConfiguredBody: string;
  oauthFailed: string;
  heroEyebrow: string;
  heroTitle1: string;
  heroTitle2: string;
  heroTitle3: string;
  heroLead: string;
  addNorBot: string;
  valueTitle: string;
  valueLead: string;
  valueFewerBotsTitle: string;
  valueFewerBotsBody: string;
  valueFewerDashboardsTitle: string;
  valueFewerDashboardsBody: string;
  valueLessFragmentationTitle: string;
  valueLessFragmentationBody: string;
  featuresTitle: string;
  featuresLead: string;
  featureCommunity: string;
  featureCommunityItems: string;
  featureModeration: string;
  featureModerationItems: string;
  featureCommunication: string;
  featureCommunicationItems: string;
  featureSupport: string;
  featureSupportItems: string;
  featureAutomation: string;
  featureAutomationItems: string;
  featureOperations: string;
  featureOperationsItems: string;
  howTitle: string;
  howLead: string;
  howLoginTitle: string;
  howLoginBody: string;
  howInstallTitle: string;
  howInstallBody: string;
  howConfigureTitle: string;
  howConfigureBody: string;
  trustTitle: string;
  trustOauthTitle: string;
  trustOauthBody: string;
  trustGuildTitle: string;
  trustGuildBody: string;
  trustPermsTitle: string;
  trustPermsBody: string;
  ctaTitle: string;
  ctaLead: string;
  footerProduct: string;
  footerTagline: string;
  langEn: string;
  langTr: string;
};

export function splitItems(value: string): string[] {
  return value.split("|").map((item) => item.trim()).filter(Boolean);
}
