"""Create the initial Discord verification schema.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-13
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the initial Discord verification tables."""

    op.create_table(
        "discord_guilds",
        sa.Column(
            "discord_guild_id",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "discord_guild_name",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "discord_owner_id",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(discord_guild_name) BETWEEN 1 AND 100",
            name="discord_guild_name_length",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("discord_guild_id"),
    )

    op.create_table(
        "configurations",
        sa.Column(
            "guild_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "verification_channel_id",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "log_channel_id",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "verified_role_id",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "unverified_role_id",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "member_role_id",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "minimum_account_age_days",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "session_timeout_seconds",
            sa.Integer(),
            server_default=sa.text("900"),
            nullable=False,
        ),
        sa.Column(
            "deny_vpn_or_proxy",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "deny_shared_ip",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "minimum_account_age_days BETWEEN 0 AND 3650",
            name="minimum_account_age_days_range",
        ),
        sa.CheckConstraint(
            "session_timeout_seconds BETWEEN 60 AND 3600",
            name="session_timeout_seconds_range",
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["discord_guilds.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id"),
    )

    op.create_table(
        "blacklisted_guilds",
        sa.Column(
            "guild_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "blacklisted_discord_guild_id",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "reason",
            sa.String(length=200),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["discord_guilds.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "guild_id",
            "blacklisted_discord_guild_id",
            name="uq_blacklisted_guilds_owner_target",
        ),
    )

    op.create_table(
        "user_list_entries",
        sa.Column(
            "guild_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "discord_user_id",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "list_type",
            sa.Enum(
                "whitelist",
                "blacklist",
                name="user_list_type",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "reason",
            sa.String(length=200),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["discord_guilds.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "guild_id",
            "discord_user_id",
            name="uq_user_list_entries_guild_user",
        ),
    )

    op.create_table(
        "verification_logs",
        sa.Column(
            "guild_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "discord_user_id",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "success",
                "failed",
                name="verification_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "reason",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "ip_hash",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "ip_encrypted",
            sa.LargeBinary(),
            nullable=False,
        ),
        sa.Column(
            "vpn_or_proxy_detected",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "shared_ip_detected",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "blacklisted_guild_detected",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["discord_guilds.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_verification_logs_discord_user_id",
        "verification_logs",
        ["discord_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_verification_logs_guild_id",
        "verification_logs",
        ["guild_id"],
        unique=False,
    )
    op.create_index(
        "ix_verification_logs_ip_hash",
        "verification_logs",
        ["ip_hash"],
        unique=False,
    )


def downgrade() -> None:
    """Remove the initial Discord verification tables."""

    op.drop_index(
        "ix_verification_logs_ip_hash",
        table_name="verification_logs",
    )
    op.drop_index(
        "ix_verification_logs_guild_id",
        table_name="verification_logs",
    )
    op.drop_index(
        "ix_verification_logs_discord_user_id",
        table_name="verification_logs",
    )

    op.drop_table("verification_logs")
    op.drop_table("user_list_entries")
    op.drop_table("blacklisted_guilds")
    op.drop_table("configurations")
    op.drop_table("discord_guilds")
