"""postgres source of truth

Revision ID: 0abbfb2f339a
Revises: 0006_logging_uniqueness
Create Date: 2026-08-08 22:04:28.947913
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

import app.models.types

revision: str = '0abbfb2f339a'
down_revision: str | Sequence[str] | None = '0006_logging_uniqueness'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_daily',
    sa.Column('guild_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('messages', sa.Integer(), nullable=False),
    sa.Column('unique_authors', sa.Integer(), nullable=False),
    sa.Column('joins', sa.Integer(), nullable=False),
    sa.Column('leaves', sa.Integer(), nullable=False),
    sa.Column('voice_uniques', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_daily')),
    sa.UniqueConstraint('guild_id', 'day', name='uq_analytics_daily_guild_day')
    )
    op.create_table('automod_configs',
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_object()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automod_configs')),
    sa.UniqueConstraint('guild_id', name=op.f('uq_automod_configs_guild_id'))
    )
    op.create_table('autoresponder_configs',
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_object()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_autoresponder_configs')),
    sa.UniqueConstraint('guild_id', name=op.f('uq_autoresponder_configs_guild_id'))
    )
    op.create_table('campaign_unsubscribes',
    sa.Column('guild_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('user_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_unsubscribes')),
    sa.UniqueConstraint('guild_id', 'user_id', name='uq_campaign_unsubscribes_guild_user')
    )
    op.create_table('campaigns',
    sa.Column('guild_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('platform_messages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_object()'), nullable=False),
    sa.Column('audience', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_object()'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_object()'), nullable=False),
    sa.Column('created_by', app.models.types.DiscordSnowflake(length=20), nullable=True),
    sa.Column('launch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index('ix_campaigns_guild_status', 'campaigns', ['guild_id', 'status'], unique=False)
    op.create_index('ix_campaigns_status_launch', 'campaigns', ['status', 'launch_at'], unique=False)
    op.create_table('discord_logging_event_types',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('group_key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('default_color', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discord_logging_event_types')),
    sa.UniqueConstraint('key', name=op.f('uq_discord_logging_event_types_key'))
    )
    op.create_table('discord_users',
    sa.Column('discord_user_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('username_cache', sa.String(length=100), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discord_users')),
    sa.UniqueConstraint('discord_user_id', name=op.f('uq_discord_users_discord_user_id'))
    )
    op.create_table('guild_module_configs',
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_object()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guild_module_configs')),
    sa.UniqueConstraint('guild_id', name=op.f('uq_guild_module_configs_guild_id'))
    )
    op.create_table('honeypot_configs',
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_object()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_honeypot_configs')),
    sa.UniqueConstraint('guild_id', name=op.f('uq_honeypot_configs_guild_id'))
    )
    op.create_table('honeypot_triggers',
    sa.Column('guild_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('user_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('channel_id', app.models.types.DiscordSnowflake(length=20), nullable=True),
    sa.Column('punishment', sa.String(length=32), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_honeypot_triggers'))
    )
    op.create_index('ix_honeypot_triggers_guild_created', 'honeypot_triggers', ['guild_id', 'created_at'], unique=False)
    op.create_table('invite_counters',
    sa.Column('guild_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('inviter_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('joins', sa.Integer(), nullable=False),
    sa.Column('leaves', sa.Integer(), nullable=False),
    sa.Column('rejoins', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invite_counters')),
    sa.UniqueConstraint('guild_id', 'inviter_id', name='uq_invite_counters_guild_inviter')
    )
    op.create_table('leveling_configs',
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_object()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leveling_configs')),
    sa.UniqueConstraint('guild_id', name=op.f('uq_leveling_configs_guild_id'))
    )
    op.create_table('member_xp',
    sa.Column('guild_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('user_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('xp', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member_xp')),
    sa.UniqueConstraint('guild_id', 'user_id', name='uq_member_xp_guild_user')
    )
    op.create_index('ix_member_xp_guild_xp', 'member_xp', ['guild_id', 'xp'], unique=False)
    op.create_table('moderation_log_entries',
    sa.Column('guild_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('target_id', app.models.types.DiscordSnowflake(length=20), nullable=True),
    sa.Column('moderator_id', app.models.types.DiscordSnowflake(length=20), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_log_entries'))
    )
    op.create_index('ix_moderation_log_entries_guild_created', 'moderation_log_entries', ['guild_id', 'created_at'], unique=False)
    op.create_table('platforms',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platforms')),
    sa.UniqueConstraint('key', name=op.f('uq_platforms_key'))
    )
    op.create_table('raid_configs',
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_object()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raid_configs')),
    sa.UniqueConstraint('guild_id', name=op.f('uq_raid_configs_guild_id'))
    )
    op.create_table('raid_incidents',
    sa.Column('guild_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('joins_count', sa.Integer(), nullable=False),
    sa.Column('join_sample', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_array()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_array()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raid_incidents'))
    )
    op.create_index('ix_raid_incidents_guild_detected', 'raid_incidents', ['guild_id', 'detected_at'], unique=False)
    op.create_table('role_menu_configs',
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_object()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_menu_configs')),
    sa.UniqueConstraint('guild_id', name=op.f('uq_role_menu_configs_guild_id'))
    )
    op.create_table('server_event_log_entries',
    sa.Column('guild_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_object()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_server_event_log_entries'))
    )
    op.create_index('ix_server_event_log_entries_guild_created', 'server_event_log_entries', ['guild_id', 'created_at'], unique=False)
    op.create_table('ticket_configs',
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_object()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_configs')),
    sa.UniqueConstraint('guild_id', name=op.f('uq_ticket_configs_guild_id'))
    )
    op.create_table('tickets',
    sa.Column('guild_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('channel_id', app.models.types.DiscordSnowflake(length=20), nullable=True),
    sa.Column('opener_id', app.models.types.DiscordSnowflake(length=20), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('guild_id', 'number', name='uq_tickets_guild_number')
    )
    op.create_index('ix_tickets_guild_status', 'tickets', ['guild_id', 'status'], unique=False)
    op.create_table('welcome_configs',
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_object()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_welcome_configs')),
    sa.UniqueConstraint('guild_id', name=op.f('uq_welcome_configs_guild_id'))
    )
    op.create_table('campaign_activity',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('jsonb_build_object()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_activity_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_activity'))
    )
    op.create_index('ix_campaign_activity_campaign', 'campaign_activity', ['campaign_id'], unique=False)
    op.create_table('campaign_recipient_results',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_recipient_results_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_recipient_results'))
    )
    op.create_index('ix_campaign_recipient_results_campaign', 'campaign_recipient_results', ['campaign_id'], unique=False)
    op.create_table('content_event_types',
    sa.Column('platform_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_content_event_types_platform_id_platforms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_event_types')),
    sa.UniqueConstraint('platform_id', 'key', name='uq_content_event_types_platform_key')
    )
    op.create_table('embed_message_channel_targets',
    sa.Column('embed_message_id', sa.Uuid(), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['embed_message_id'], ['embed_messages.id'], name=op.f('fk_embed_message_channel_targets_embed_message_id_embed_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embed_message_channel_targets')),
    sa.UniqueConstraint('embed_message_id', 'channel_id', name='uq_embed_message_channel_targets_message_channel')
    )
    op.create_index('ix_embed_message_channel_targets_guild_id', 'embed_message_channel_targets', ['guild_id'], unique=False)
    op.create_table('guilds',
    sa.Column('discord_guild_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(name) BETWEEN 1 AND 100', name=op.f('ck_guilds_guild_name_length')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['discord_users.id'], name=op.f('fk_guilds_owner_user_id_discord_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guilds')),
    sa.UniqueConstraint('discord_guild_id', name=op.f('uq_guilds_discord_guild_id'))
    )
    op.create_table('system_audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', app.models.types.DiscordSnowflake(length=20), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['discord_users.id'], name=op.f('fk_system_audit_log_actor_id_discord_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_audit_log'))
    )
    op.create_index(op.f('ix_system_audit_log_created_at'), 'system_audit_log', ['created_at'], unique=False)
    op.create_index('ix_system_audit_log_entity', 'system_audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_system_audit_log_guild_created', 'system_audit_log', ['guild_id', 'created_at'], unique=False)
    op.create_table('ticket_share_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('guild_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_share_tokens_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_ticket_share_tokens'))
    )
    op.create_table('ticket_transcripts',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_transcripts_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_transcripts')),
    sa.UniqueConstraint('ticket_id', name=op.f('uq_ticket_transcripts_ticket_id'))
    )
    op.create_table('guild_blacklisted_guilds',
    sa.Column('guild_id', sa.Uuid(), nullable=False),
    sa.Column('blacklisted_discord_guild_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_guild_blacklisted_guilds_guild_id_guilds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guild_blacklisted_guilds')),
    sa.UniqueConstraint('guild_id', 'blacklisted_discord_guild_id', name='uq_guild_blacklisted_guilds_owner_target')
    )
    op.create_table('guild_channel_bindings',
    sa.Column('guild_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('verification', 'log', name='guild_channel_purpose', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('channel_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_guild_channel_bindings_guild_id_guilds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guild_channel_bindings')),
    sa.UniqueConstraint('guild_id', 'purpose', name='uq_guild_channel_bindings_guild_purpose')
    )
    op.create_table('guild_moderation_entries',
    sa.Column('guild_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('list_type', sa.Enum('whitelist', 'blacklist', name='user_list_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_guild_moderation_entries_guild_id_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['discord_users.id'], name=op.f('fk_guild_moderation_entries_user_id_discord_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guild_moderation_entries')),
    sa.UniqueConstraint('guild_id', 'user_id', name='uq_guild_moderation_entries_guild_user')
    )
    op.create_table('guild_role_bindings',
    sa.Column('guild_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('verified', 'unverified', 'member', name='guild_role_purpose', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('role_id', app.models.types.DiscordSnowflake(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_guild_role_bindings_guild_id_guilds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guild_role_bindings')),
    sa.UniqueConstraint('guild_id', 'purpose', name='uq_guild_role_bindings_guild_purpose')
    )
    op.create_table('guild_settings',
    sa.Column('guild_id', sa.Uuid(), nullable=False),
    sa.Column('minimum_account_age_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('session_timeout_seconds', sa.Integer(), server_default='900', nullable=False),
    sa.Column('deny_vpn_or_proxy', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deny_shared_ip', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('minimum_account_age_days BETWEEN 0 AND 3650', name=op.f('ck_guild_settings_minimum_account_age_days_range')),
    sa.CheckConstraint('session_timeout_seconds BETWEEN 60 AND 3600', name=op.f('ck_guild_settings_session_timeout_seconds_range')),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_guild_settings_guild_id_guilds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guild_settings')),
    sa.UniqueConstraint('guild_id', name=op.f('uq_guild_settings_guild_id'))
    )
    op.create_table('verification_attempts',
    sa.Column('guild_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='verification_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('vpn_or_proxy_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('shared_ip_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('blacklisted_guild_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name=op.f('fk_verification_attempts_guild_id_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['discord_users.id'], name=op.f('fk_verification_attempts_user_id_discord_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_attempts'))
    )
    op.create_index(op.f('ix_verification_attempts_guild_id'), 'verification_attempts', ['guild_id'], unique=False)
    op.create_index(op.f('ix_verification_attempts_ip_hash'), 'verification_attempts', ['ip_hash'], unique=False)
    op.create_index(op.f('ix_verification_attempts_user_id'), 'verification_attempts', ['user_id'], unique=False)
    # Drop child tables (all FK to discord_guilds) before the parent.
    op.drop_index(op.f('ix_verification_logs_discord_user_id'), table_name='verification_logs')
    op.drop_index(op.f('ix_verification_logs_guild_id'), table_name='verification_logs')
    op.drop_index(op.f('ix_verification_logs_ip_hash'), table_name='verification_logs')
    op.drop_table('verification_logs')
    op.drop_table('blacklisted_guilds')
    op.drop_table('configurations')
    op.drop_table('user_list_entries')
    op.drop_table('discord_guilds')
    op.alter_column('embed_message_deliveries', 'delivery_type',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('embed_message_deliveries', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('embed_messages', 'description',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('embed_messages', 'content',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('embed_messages', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('logging_channels', 'norgoth_managed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('logging_channels', 'position',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('logging_configurations', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('logging_configurations', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('logging_configurations', 'norgoth_managed_category',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('logging_event_mappings', sa.Column('event_type_id', sa.Uuid(), nullable=True))
    op.alter_column('logging_event_mappings', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_foreign_key('fk_logging_event_type_id', 'logging_event_mappings', 'discord_logging_event_types', ['event_type_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_logging_event_type_id', 'logging_event_mappings', type_='foreignkey')
    op.alter_column('logging_event_mappings', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('logging_event_mappings', 'event_type_id')
    op.alter_column('logging_configurations', 'norgoth_managed_category',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('logging_configurations', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'draft'::character varying"),
               existing_nullable=False)
    op.alter_column('logging_configurations', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('logging_channels', 'position',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('logging_channels', 'norgoth_managed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('embed_messages', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('embed_messages', 'content',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.alter_column('embed_messages', 'description',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.alter_column('embed_message_deliveries', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('embed_message_deliveries', 'delivery_type',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'bot'::character varying"),
               existing_nullable=False)
    op.create_table('verification_logs',
    sa.Column('guild_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('discord_user_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ip_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('ip_encrypted', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('vpn_or_proxy_detected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('shared_ip_detected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('blacklisted_guild_detected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['success'::character varying, 'failed'::character varying]::text[])", name=op.f('ck_verification_logs_verification_status')),
    sa.ForeignKeyConstraint(['guild_id'], ['discord_guilds.id'], name=op.f('fk_verification_logs_guild_id_discord_guilds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_logs'))
    )
    op.create_index(op.f('ix_verification_logs_ip_hash'), 'verification_logs', ['ip_hash'], unique=False)
    op.create_index(op.f('ix_verification_logs_guild_id'), 'verification_logs', ['guild_id'], unique=False)
    op.create_index(op.f('ix_verification_logs_discord_user_id'), 'verification_logs', ['discord_user_id'], unique=False)
    op.create_table('discord_guilds',
    sa.Column('discord_guild_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('discord_guild_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('discord_owner_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('char_length(discord_guild_name::text) >= 1 AND char_length(discord_guild_name::text) <= 100', name=op.f('ck_discord_guilds_discord_guild_name_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discord_guilds')),
    sa.UniqueConstraint('discord_guild_id', name=op.f('uq_discord_guilds_discord_guild_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_list_entries',
    sa.Column('guild_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('discord_user_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('list_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("list_type::text = ANY (ARRAY['whitelist'::character varying, 'blacklist'::character varying]::text[])", name=op.f('ck_user_list_entries_user_list_type')),
    sa.ForeignKeyConstraint(['guild_id'], ['discord_guilds.id'], name=op.f('fk_user_list_entries_guild_id_discord_guilds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_list_entries')),
    sa.UniqueConstraint('guild_id', 'discord_user_id', name=op.f('uq_user_list_entries_guild_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('configurations',
    sa.Column('guild_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('verification_channel_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('log_channel_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('verified_role_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('unverified_role_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('member_role_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('minimum_account_age_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('session_timeout_seconds', sa.INTEGER(), server_default=sa.text('900'), autoincrement=False, nullable=False),
    sa.Column('deny_vpn_or_proxy', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('deny_shared_ip', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('minimum_account_age_days >= 0 AND minimum_account_age_days <= 3650', name=op.f('ck_configurations_minimum_account_age_days_range')),
    sa.CheckConstraint('session_timeout_seconds >= 60 AND session_timeout_seconds <= 3600', name=op.f('ck_configurations_session_timeout_seconds_range')),
    sa.ForeignKeyConstraint(['guild_id'], ['discord_guilds.id'], name=op.f('fk_configurations_guild_id_discord_guilds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configurations')),
    sa.UniqueConstraint('guild_id', name=op.f('uq_configurations_guild_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('blacklisted_guilds',
    sa.Column('guild_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('blacklisted_discord_guild_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['discord_guilds.id'], name=op.f('fk_blacklisted_guilds_guild_id_discord_guilds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blacklisted_guilds')),
    sa.UniqueConstraint('guild_id', 'blacklisted_discord_guild_id', name=op.f('uq_blacklisted_guilds_owner_target'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_verification_attempts_user_id'), table_name='verification_attempts')
    op.drop_index(op.f('ix_verification_attempts_ip_hash'), table_name='verification_attempts')
    op.drop_index(op.f('ix_verification_attempts_guild_id'), table_name='verification_attempts')
    op.drop_table('verification_attempts')
    op.drop_table('guild_settings')
    op.drop_table('guild_role_bindings')
    op.drop_table('guild_moderation_entries')
    op.drop_table('guild_channel_bindings')
    op.drop_table('guild_blacklisted_guilds')
    op.drop_table('ticket_transcripts')
    op.drop_table('ticket_share_tokens')
    op.drop_index('ix_system_audit_log_guild_created', table_name='system_audit_log')
    op.drop_index('ix_system_audit_log_entity', table_name='system_audit_log')
    op.drop_index(op.f('ix_system_audit_log_created_at'), table_name='system_audit_log')
    op.drop_table('system_audit_log')
    op.drop_table('guilds')
    op.drop_index('ix_embed_message_channel_targets_guild_id', table_name='embed_message_channel_targets')
    op.drop_table('embed_message_channel_targets')
    op.drop_table('content_event_types')
    op.drop_index('ix_campaign_recipient_results_campaign', table_name='campaign_recipient_results')
    op.drop_table('campaign_recipient_results')
    op.drop_index('ix_campaign_activity_campaign', table_name='campaign_activity')
    op.drop_table('campaign_activity')
    op.drop_table('welcome_configs')
    op.drop_index('ix_tickets_guild_status', table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('ticket_configs')
    op.drop_index('ix_server_event_log_entries_guild_created', table_name='server_event_log_entries')
    op.drop_table('server_event_log_entries')
    op.drop_table('role_menu_configs')
    op.drop_index('ix_raid_incidents_guild_detected', table_name='raid_incidents')
    op.drop_table('raid_incidents')
    op.drop_table('raid_configs')
    op.drop_table('platforms')
    op.drop_index('ix_moderation_log_entries_guild_created', table_name='moderation_log_entries')
    op.drop_table('moderation_log_entries')
    op.drop_index('ix_member_xp_guild_xp', table_name='member_xp')
    op.drop_table('member_xp')
    op.drop_table('leveling_configs')
    op.drop_table('invite_counters')
    op.drop_index('ix_honeypot_triggers_guild_created', table_name='honeypot_triggers')
    op.drop_table('honeypot_triggers')
    op.drop_table('honeypot_configs')
    op.drop_table('guild_module_configs')
    op.drop_table('discord_users')
    op.drop_table('discord_logging_event_types')
    op.drop_index('ix_campaigns_status_launch', table_name='campaigns')
    op.drop_index('ix_campaigns_guild_status', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('campaign_unsubscribes')
    op.drop_table('autoresponder_configs')
    op.drop_table('automod_configs')
    op.drop_table('analytics_daily')
    # ### end Alembic commands ###
